travis:
  secure:
    BINSTAR_TOKEN: i84y1NhloGjNNVTqpFfMiAm6eruwgJEofz3AsJckXodJD2uZdYLNQRBIMCu0IaOQDVPYkeSPjxPyLaWZ5iT9/mr/z135cVxKBSTzY8hvaThPN4dVX9egPPUV1WTDwYzAGhmDxRMC11FVnOhXp0P1ZDlNUwYfyZaXOnC8fSMMcg3XQNt+rofIR9wI5j2FpDF4Y2gdGpHoaIlT8Y+lmTLAe/hUotvL59T9u/5VDfOgvB0Be+dQBmLiOBuuuPjbiZdeI4IqRmGFjv6hqTpTrD8Jt8tbORO1x3n6Ndje+nrnDNBVv9p2zrnNrOrK5oJgzOuTeWZLGa1RGMoxBl7fifpUXn9i16RbkyMizT0cyzKhtYsrQPhZZyV+4XgQ4QI2r6PoVajo6EcGeWyV+r3Y4j5iVVlLMbu32bbppCWnCtry2ZQpky3NnS2v2x4Jbl3oK1D/qWwGHtKC7G3XU90BhrZm0YTjUxfu2CuHxq2e8BPZ8lPstYDtfiHLyLTHzdvd8aQHzQQAmJtKZnACgbyFoLaKtPZPqfaJVQmvTHMJDvOFZ+230BapMRC9IuUIfsFiqislQrvWCRaHBup4q0MuDeimBC+jwjsD6KHQ/J2C+RiXSC3d+KQlVmz+YLfOx+XhIvh//X9M1c+crx8Xn/lRfNL3nv/0OOdfzsjvHNmcyu4cT88=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
