travis:
  secure:
    BINSTAR_TOKEN: iYCTYsAbqGCSU+OOmK7oPy8DYISWAvlU6ZFkbY0iokoVabr8S5sTrmE+xwtaScrXAUxaa2tZ4IoxjWU1qzY70ghooeYj0ee7g4BsocsMt66SFBsLqw1FkHPB8BYuOp00+nB7zwLbL5dLfmnvMq837VwV9A2/73QJzL/tqOiqqG91wimCvRMhFHJM28vnyKcPWxqjVFGmTBaaYfHMSI8qsgwhqgP6VKdGu20gfMeAvDDP8Jzbhva+F2OmtRwX0LyWQtMRo+IZkVhWF8MDWlE9h5I60l+L7AQPhGbgGilOMXCeLXVJ8fM2yEh0shivk4WYKa97wUZ/OPWOZdubNgzJI2sLGAyk6MobPe5COPr3KUfEiD/FJZu/qsYvLRyJi4IelPmBIurYx+DMqB4P8QO76KEk4ukJ8FAYWUuQ5kuW0botdthiFVXGwrqSxT4mAkyrCSSawsNVaWAg+JnxozXf5T+auufhQZi3aF0vFqdFM9DDl+fu37SOtUXXamzKYGolF6kwKZZwlm7m4tF3Cr+rQUYWToFbhFimVIF6ODbLfbF7oRm5+COIX0uaWLBiJVN2mmgH57dvZtIhvqyfDMfK+7znvOEOKa9hJvUp7zhpGDzUgicm/VxMG5pk/OOZ4vaa065l5DWYH+hzE/dbCEcDynh9EeBPEzgI1AcplJ9ac80=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
